apiVersion: batch/v1
kind: Job
metadata:
  name: time-sync-job
spec:
  template:
    spec:
      containers:
      - name: time-sync
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["while true; do pod_time=$(date +%s); atomic_time=$(curl -s http://worldclockapi.com/api/json/utc/now | jq -r '.currentFileTimeUnix'); time_diff=$((atomic_time - pod_time)); echo 'Time on pod: ' && date && echo 'Current atomic time: ' && curl -s --head http://worldclockapi.com/api/json/utc/now | grep -i date && echo 'Time difference (in seconds): ' $time_diff; sleep 10; done"]
        env:
        - name: TZ
          value: "YOUR_TIMEZONE"  # replace with your desired timezone
        - name: LANG
          value: "en_US.UTF-8"  # adjust language settings if needed
        - name: LC_ALL
          value: "en_US.UTF-8"  # adjust language settings if needed
      restartPolicy: OnFailure
  backoffLimit: 4
