apiVersion: batch/v1
kind: Job
metadata:
  name: time-job
spec:
  template:
    spec:
      containers:
      - name: time
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y dnsutils curl jq && while true; do pod_time=$(date +%s); atomic_time=$(curl -s http://www.worldtimeapi.org/api/timezone/Etc/UTC | jq -r '.unixtime');  echo 'Time on pod: '&& echo $pod_time ;  echo 'Current atomic time: ' && echo $atomic_time ; sleep 600; done"]
        env:
        - name: TZ
          value: "YOUR_TIMEZONE"  # replace with your desired timezone
        - name: LANG
          value: "en_US.UTF-8"  # adjust language settings if needed
        - name: LC_ALL
          value: "en_US.UTF-8"  # adjust language settings if needed
      restartPolicy: OnFailure
